In [4]:
import numpy as np
import torch

31. warning

In [5]:
import warnings
warnings.filterwarnings("ignore")

In [6]:
np.sqrt(-1)
np.emath.sqrt(-1) == np.sqrt(-1)
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
yesterday
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1, 'D')
tomorrow
Z = np.arange('2016-07','2016-08',dtype='datetime64[D]')
Z

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

35. 在不复制值的情况下做原地计算（（A+B）*-(A/2)）

In [7]:
A = torch.rand([3,3])
B = torch.rand([3,3])
B = A+B
B*(-A/2)

A = torch.ones(3)*1
B = torch.ones(3) * 2
torch.add(A,B, out=B)
torch.div(A,2, out=A)
torch.neg_(A)
torch.mul(A, B, out=B)
B

tensor([-1.5000, -1.5000, -1.5000])

36. 使用5中不同方法提取Tensor中每个元素的整数部分

In [8]:
Z = torch.rand([2,2])*5
print(Z)
# 1
Z1 = Z.int()
# Z1 = Z.astype(int)
Z1 = Z.type(torch.int)
print("1:", Z1)
Z2 = torch.floor(Z)
print('2:', Z2)
Z3 = Z - Z%1
print("3:", Z3)
Z4 = torch.ceil(Z)-1
print("4:", Z4)
print("5:", torch.trunc(Z))
a = torch.arange(5)
# print(a)
b = torch.ones([5,5])
b[:] = a
print(b)
print(torch.arange(5).repeat(5,1))

tensor([[0.6077, 4.1125],
        [3.3231, 2.0427]])
1: tensor([[0, 4],
        [3, 2]], dtype=torch.int32)
2: tensor([[0., 4.],
        [3., 2.]])
3: tensor([[0., 4.],
        [3., 2.]])
4: tensor([[0., 4.],
        [3., 2.]])
5: tensor([[0., 4.],
        [3., 2.]])
tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


38. 创建一个生成器函数，用于生成10个整数，并用这个生成器函数创建一个一维Tensor

In [9]:
generator = (i for i in range(10))
tensor = torch.tensor(list(generator))
# tensor

def g():
    yield from range(10)
torch.from_numpy(np.fromiter(g(), dtype=np.int))
torch.linspace(0,1,12)[1:-1]
torch.linspace(0,1,12)[1:-1]
a = torch.rand(10)
print(a)
print(a.sort())
a.sort()
print(a)
print(sorted(a))
torch.sort(a)


tensor([0.4328, 0.5807, 0.5709, 0.8513, 0.9274, 0.3693, 0.7886, 0.6507, 0.4391,
        0.4993])
torch.return_types.sort(
values=tensor([0.3693, 0.4328, 0.4391, 0.4993, 0.5709, 0.5807, 0.6507, 0.7886, 0.8513,
        0.9274]),
indices=tensor([5, 0, 8, 9, 2, 1, 7, 6, 3, 4]))
tensor([0.4328, 0.5807, 0.5709, 0.8513, 0.9274, 0.3693, 0.7886, 0.6507, 0.4391,
        0.4993])
[tensor(0.3693), tensor(0.4328), tensor(0.4391), tensor(0.4993), tensor(0.5709), tensor(0.5807), tensor(0.6507), tensor(0.7886), tensor(0.8513), tensor(0.9274)]


torch.return_types.sort(
values=tensor([0.3693, 0.4328, 0.4391, 0.4993, 0.5709, 0.5807, 0.6507, 0.7886, 0.8513,
        0.9274]),
indices=tensor([5, 0, 8, 9, 2, 1, 7, 6, 3, 4]))

41. 对于小向量求和时，如何计算才能比使用np.sum更快？
注：在numpy中，可以使用np.add.reduce, 在小向量计算速度上快于np.sum。但pyTorch似乎没有对应的方法，经测试，对torch.arange(10)进行求和时，torch.sum仍然快于np.add.reduce

In [10]:
import time
start_time = time.time()
Z = np.arange(10)
np.add.reduce(Z)
end_time = time.time()
print(end_time-start_time)
start_time = time.time()
Z = torch.arange(10)
torch.sum(Z)
end_time = time.time()
print(end_time-start_time)


0.0001938343048095703
0.0008137226104736328


41.给定两个随机TensorA和B，判断是否相等

In [11]:
A = torch.rand([3,4])
B = torch.rand([3,4])
C = A
print((A == B).sum() == A.numel())
print((A == C).sum() == A.numel())
# 检查值是否精确相等
print(torch.equal(torch.Tensor([1.1, 2.1]), torch.Tensor([1,2])))
# torch.Tensor是一个类，而torch.tensor是一个函数
# 更经常使用torch.tensor，因为它更方便，有自动的类型转换
# 而torch.Tensor确定为torch.float类型
print(torch.equal(torch.tensor([1.1, 2.1]), torch.tensor([1, 2], dtype=torch.float)))
print(torch.allclose(torch.tensor([1.1,2.1]), torch.tensor([1,2], dtype=torch.float), atol=0.1))


tensor(False)
tensor(True)
False
False
True


43. 将Tensor转变为只读

In [12]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 2 # read only -> ValueError
A = torch.rand([10,2])*5
# print(A)
B = torch.zeros([10,2])
B[:,0] = torch.sqrt(A.square().sum(dim=1))
B[:,1] = torch.arccos(A[:,0]/ B[:,0])
print(B)
X = A[:,0]
Y = A[:,1]
R = torch.sqrt(X**2 + Y**2)
T = torch.atan(Y/X)
torch.stack([R,T],dim=1)

tensor([[3.9924, 0.8430],
        [0.3228, 1.4117],
        [5.3066, 0.4686],
        [1.9566, 0.8032],
        [5.5294, 0.9891],
        [3.4549, 0.2554],
        [5.8452, 0.8802],
        [2.3860, 0.0654],
        [5.0265, 0.9140],
        [2.8753, 1.0491]])


tensor([[3.9924, 0.8430],
        [0.3228, 1.4117],
        [5.3066, 0.4686],
        [1.9566, 0.8032],
        [5.5294, 0.9891],
        [3.4549, 0.2554],
        [5.8452, 0.8802],
        [2.3860, 0.0654],
        [5.0265, 0.9140],
        [2.8753, 1.0491]])

In [13]:
t = torch.rand(10)
print(t)
t[torch.argmax(t)] = 0
print(t)
X = torch.linspace(0,1,5)
Z = torch.ones(len(X))
coord = torch.stack([X,X,Z],dim=1)
coord

tensor([0.0642, 0.5919, 0.3882, 0.3786, 0.2815, 0.2714, 0.9014, 0.2193, 0.6944,
        0.7569])
tensor([0.0642, 0.5919, 0.3882, 0.3786, 0.2815, 0.2714, 0.0000, 0.2193, 0.6944,
        0.7569])


tensor([[0.0000, 0.0000, 1.0000],
        [0.2500, 0.2500, 1.0000],
        [0.5000, 0.5000, 1.0000],
        [0.7500, 0.7500, 1.0000],
        [1.0000, 1.0000, 1.0000]])

46. 在直角坐标轴上 (0,0) 到 (1,1) 区域内放一个 5x5 的网格，创建一个5x5x2 的 Tensor，其值对应网格中每个点的坐标

In [14]:
X,Y = torch.meshgrid(torch.linspace(0,1,5),
                     torch.linspace(0,1,5))
torch.stack([X,Y],dim=2)


tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000]],

        [[0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000]],

        [[0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000]],

        [[0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000]],

        [[1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])

47. 给定两个向量X,Y, 创建一个柯西矩阵C(Cij=1/(xi-yj))

In [15]:
X = torch.arange(5)
Y = torch.ones(5)*3
C = torch.ones([5,5])
X.view([-1,1])
print(X.view([-1,1]).shape)
print(X.view([-1,1]) - Y)
torch.div(1, X.view([-1,1]) - Y)


torch.Size([5, 1])
tensor([[-3., -3., -3., -3., -3.],
        [-2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.]])


tensor([[-0.3333, -0.3333, -0.3333, -0.3333, -0.3333],
        [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [    inf,     inf,     inf,     inf,     inf],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000]])

48. 打印PyTorch Tensor每一种标量数据结构的最大和最小可表示数(representable value)

In [16]:
for dtype in [torch.int8, torch.int32, torch.int64]:
    print(torch.iinfo(dtype).min)
    print(torch.iinfo(dtype).max)

print("=="*8)
for dtype in [torch.float32, torch.float64]:
    print(torch.finfo(dtype).min)
    print(torch.finfo(dtype).max)
    print(torch.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028234663852886e+38
3.4028234663852886e+38
1.1920928955078125e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何完整显示 Tensor 的所有值? 

In [17]:
# torch.set_printoptions(threshold=float('NaN'))
Z = torch.zeros([16,16])
print(Z)
torch.set_printoptions(threshold=1000)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

50. 给定一个标量和一个向量，找出向量中与给定标量值最接近的元素

In [18]:
t = torch.rand(5)
print(t)
scalar = 0.08
b = torch.square(t-scalar)
print(t[torch.argmin(b)])
i = torch.abs(t-scalar).argmin()
print(t[i])

tensor([0.3931, 0.3437, 0.2906, 0.2759, 0.5262])
tensor(0.2759)
tensor(0.2759)


52. 给定一个(100,2)的矩阵，每行表示一个点的坐标。计算所有点两两之间的距离。

In [33]:
A = torch.rand(100,2)*100
def dist_2points(point1, point2):
    vec = point2 - point1
    return torch.sqrt(torch.square(vec).sum())
def dist_2rows(matrix, i, j):
    vec1 = matrix[i,:]
    vec2 = matrix[j,:]
    return dist_2points(vec1, vec2)
print(f"pointA:{A[0,:]}, pointB:{A[5,:]}的距离")
dist_2rows(A, 0, 5)
t = torch.rand([5,2])
X = t[:,0].view([1,-1])
Y = t[:,1].view([1,-1])
print(torch.sqrt((X-X.T)**2 + (Y-Y.T)**2))

# 第二种，使用scipy
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(t,t)
D


pointA:tensor([82.4957, 85.4137]), pointB:tensor([22.5277, 94.3432])的距离
tensor([[0.0000, 0.9274, 0.4293, 0.5480, 0.4425],
        [0.9274, 0.0000, 0.5563, 0.4655, 0.7441],
        [0.4293, 0.5563, 0.0000, 0.1189, 0.2234],
        [0.5480, 0.4655, 0.1189, 0.0000, 0.2794],
        [0.4425, 0.7441, 0.2234, 0.2794, 0.0000]])


array([[0.        , 0.92742518, 0.42925856, 0.54795354, 0.44251242],
       [0.92742518, 0.        , 0.55628736, 0.46553155, 0.74406333],
       [0.42925856, 0.55628736, 0.        , 0.11889857, 0.22335627],
       [0.54795354, 0.46553155, 0.11889857, 0.        , 0.27939013],
       [0.44251242, 0.74406333, 0.22335627, 0.27939013, 0.        ]])

53. 原地将一个浮点型(32 bits) Tensor 转换为整型(32 bits)

In [34]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:]=Z
print(Y)

[27 47 86 43  4 59 52 99 71 48]


54. 将一下内容的Tensor保存至硬盘，并再次读取


In [ ]:
T = torch.tensor([[1,2,3],
                  [8,9,7],
                  [10, 11, 12]])
torch.save(T,'tensor.pt')
load_tensor = torch.load('tensor.pt')
print(load_tensor)


tensor([[ 1,  2,  3],
        [ 8,  9,  7],
        [10, 11, 12]])


55. enumerate 函数在PyTorch中对应的函数是什么

In [44]:
Z = np.arange(9).reshape(3,3,1)
# ndenumerate 是每一个元素
for index, value in np.ndenumerate(Z):
    print(index, value)

# enumerate 是每一行
for index,value in enumerate(Z):
    print(value, index)


(0, 0, 0) 0
(0, 1, 0) 1
(0, 2, 0) 2
(1, 0, 0) 3
(1, 1, 0) 4
(1, 2, 0) 5
(2, 0, 0) 6
(2, 1, 0) 7
(2, 2, 0) 8
[[0]
 [1]
 [2]] 0
[[3]
 [4]
 [5]] 1
[[6]
 [7]
 [8]] 2


In [45]:
np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

[array([[-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.3333333

57.一个矩阵中随机选p个元素，并替换成其他值

In [49]:
A = torch.ones([5,5])
a = torch.randint(0,5,[3])
b = torch.randint(0,5,[3])
print(A)
A[a,b] = 10
print(A)
p = 3
t = torch.zeros([3,3])
indices = torch.from_numpy(np.random.choice(range(9),p))
# accumulate在重复索引时，可以累加， 正常就是替换值
t.put_(indices, torch.rand(p), accumulate=True)



tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1., 10., 10.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1., 10.,  1.]])


tensor([[0.0000, 0.0000, 0.3733],
        [0.0000, 0.0114, 0.0000],
        [0.0000, 0.0000, 0.6212]])

58. 给定一个矩阵，计算每个元素减去所在行的平均数


In [73]:
A = torch.rand([5,5])
A_np = A.numpy()
### 注意keepdim=True
# 计算列均值
col_means = np.mean(A_np, axis=1, keepdims=True)  # 形状 (5,)

# 每个元素减去对应行的均值
B = A_np - col_means 
print(B)
print(A - torch.mean(A,dim=1, keepdim=True))
Y = A - A.mean(axis=1,keepdim=True)
Y
X = torch.arange(10).view([2,5]).type(torch.float32)
print("nokeepdim," ,torch.mean(X,dim=1))
print("withkeepdim,", torch.mean(X,dim=1, keepdim=True))




[[-0.08576638 -0.27017367  0.0054884   0.1885379   0.16191345]
 [-0.11502016 -0.21105373  0.12959945 -0.23809743  0.43457168]
 [-0.3463961  -0.35653335 -0.2065599   0.5909062   0.31858307]
 [ 0.15395665 -0.14002252 -0.17706692 -0.09539092  0.25852346]
 [ 0.07746977 -0.32236254  0.2367168   0.16645533 -0.15827954]]
tensor([[-0.0858, -0.2702,  0.0055,  0.1885,  0.1619],
        [-0.1150, -0.2111,  0.1296, -0.2381,  0.4346],
        [-0.3464, -0.3565, -0.2066,  0.5909,  0.3186],
        [ 0.1540, -0.1400, -0.1771, -0.0954,  0.2585],
        [ 0.0775, -0.3224,  0.2367,  0.1665, -0.1583]])
nokeepdim, tensor([2., 7.])
withkeepdim, tensor([[2.],
        [7.]])


59. 给定一个矩阵，根据第n列的值对行进行排序

In [ ]:
M = torch.randint(0, 10, [5,2])
n = 1
_, indices = M[:,n].sort()
M = M[indices]

torch.return_types.sort(
values=tensor([5, 5, 7, 8, 9]),
indices=tensor([0, 4, 1, 2, 3]))