In [32]:
import numpy as np
import torch

In [33]:
t = torch.tensor([1,2,4,0,0,1,3,0])
print(t.nonzero())
t[t.nonzero().squeeze()] = -1
print(t)
mask = t==0
t[~t.bool()] = 1 # equal to t[mask] = 1
print(t)


tensor([[0],
        [1],
        [2],
        [5],
        [6]])
tensor([-1, -1, -1,  0,  0, -1, -1,  0])
tensor([-1, -1, -1,  1,  1, -1, -1,  1])


In [34]:
a = set([1,2,3,5,1,1,4,9,'s'])
print(a)
print('s' in a)
print(8 in a)
print(2 in a)

{1, 2, 3, 4, 5, 9, 's'}
True
False
True


In [35]:
t = torch.ones([2,2])
a = torch.nn.functional.pad(t,(1,1,1,1), mode="constant", value=0)
print(a)
print(a.size())
print(a.view(16))


tensor([[0., 0., 0., 0.],
        [0., 1., 1., 0.],
        [0., 1., 1., 0.],
        [0., 0., 0., 0.]])
torch.Size([4, 4])
tensor([0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0.])


In [36]:
below_diagonal = torch.Tensor([1,2,3,4])
print(torch.diag(below_diagonal, diagonal=1))
t = torch.zeros((8,8), dtype=int)
t[1::2,::2] =1
t[::2, 1::2] = -1
print(t)


tensor([[0., 1., 0., 0., 0.],
        [0., 0., 2., 0., 0.],
        [0., 0., 0., 3., 0.],
        [0., 0., 0., 0., 4.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0, -1,  0, -1,  0, -1,  0, -1],
        [ 1,  0,  1,  0,  1,  0,  1,  0],
        [ 0, -1,  0, -1,  0, -1,  0, -1],
        [ 1,  0,  1,  0,  1,  0,  1,  0],
        [ 0, -1,  0, -1,  0, -1,  0, -1],
        [ 1,  0,  1,  0,  1,  0,  1,  0],
        [ 0, -1,  0, -1,  0, -1,  0, -1],
        [ 1,  0,  1,  0,  1,  0,  1,  0]])


In [37]:
t= torch.Tensor([[0,1],[1,0]])
print(t.repeat([4,3]))
t = torch.rand([5,5])
print((t-t.mean())/t.std())
5 //4

tensor([[0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0.],
        [0., 1., 0., 1., 0., 1.],
        [1., 0., 1., 0., 1., 0.]])
tensor([[-1.3605, -0.4815,  0.0240, -0.1746, -0.3165],
        [ 0.3797, -0.2839, -0.3451,  0.7763, -1.0035],
        [ 0.6386,  0.4955,  1.7062, -1.4454,  1.1355],
        [ 1.5848, -0.8069,  0.0640,  1.3672, -1.4733],
        [-0.0807,  1.7247, -1.1794, -1.1297,  0.1846]])


1

29. 将float类型的Tensor中元素进位转换为整数
round away from zero, i.e. 3.2 => 4, -3.2 => -4

In [38]:
t = torch.randn([2,3]) * 3
print(t)
print(torch.floor(torch.tensor([5.9])))
torch.mul(torch.sign(t), torch.ceil(torch.abs(t)))


tensor([[ 2.6550, -0.3341,  0.4113],
        [-4.5893,  3.9331,  2.4995]])
tensor([5.])


tensor([[ 3., -1.,  1.],
        [-5.,  4.,  3.]])

30. 找出两个一维Tensor都出现的元素

In [39]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1, Z2))

[0 1 2 7 8 9]


31. warning

In [40]:
import warnings
warnings.filterwarnings("ignore")

In [41]:
np.sqrt(-1)
np.emath.sqrt(-1) == np.sqrt(-1)
yesterday = np.datetime64('today','D') - np.timedelta64(1, 'D')
yesterday
today = np.datetime64('today','D')
tomorrow = np.datetime64('today','D') + np.timedelta64(1, 'D')
tomorrow
Z = np.arange('2016-06','2016-08',dtype='datetime64[D]')
Z

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30', '2016-07-01', '2016-07-02',
       '2016-07-03', '2016-07-04', '2016-07-05', '2016-07-06',
       '2016-07-07', '2016-07-08', '2016-07-09', '2016-07-10',
       '2016-07-11', '2016-07-12', '2016-07-13', '2016-07-14',
       '2016-07-15', '2016-07-16', '2016-07-17', '2016-07-18',
       '2016-07-19', '2016-07-20', '2016-07-21', '2016-07-22',
       '2016-07-23', '2016-07-24', '2016-07-25', '2016-07-26',
       '2016-07-27', '2016-07-28', '2016-07-29', '2016-07-30',
       '2016-07-31'], dtype='datetime64[D]')

35. 在不复制值的情况下做原地计算（（A+B）*-(A/2)）

In [42]:
A = torch.rand([3,3])
B = torch.rand([3,3])
B = A+B
B*(-A/2)

A = torch.ones(3)*1
B = torch.ones(3) * 2
torch.add(A,B, out=B)
torch.div(A,2, out=A)
torch.neg_(A)
torch.mul(A, B, out=B)
B

tensor([-1.5000, -1.5000, -1.5000])

36. 使用5中不同方法提取Tensor中每个元素的整数部分

In [43]:
Z = torch.rand([2,2])*5
print(Z)
# 1
Z1 = Z.int()
# Z1 = Z.astype(int)
Z1 = Z.type(torch.int)
print("1:", Z1)
Z2 = torch.floor(Z)
print('2:', Z2)
Z3 = Z - Z%1
print("3:", Z3)
Z4 = torch.ceil(Z)-1
print("4:", Z4)
print("5:", torch.trunc(Z))
a = torch.arange(5)
# print(a)
b = torch.ones([5,5])
b[:] = a
print(b)
print(torch.arange(5).repeat(5,1))

tensor([[0.6825, 4.1340],
        [4.2248, 3.7058]])
1: tensor([[0, 4],
        [4, 3]], dtype=torch.int32)
2: tensor([[0., 4.],
        [4., 3.]])
3: tensor([[0., 4.],
        [4., 3.]])
4: tensor([[0., 4.],
        [4., 3.]])
5: tensor([[0., 4.],
        [4., 3.]])
tensor([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]])
tensor([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])


38. 创建一个生成器函数，用于生成10个整数，并用这个生成器函数创建一个一维Tensor

In [44]:
generator = (i for i in range(10))
tensor = torch.tensor(list(generator))
# tensor

def g():
    yield from range(10)
torch.from_numpy(np.fromiter(g(), dtype=np.int))
torch.linspace(0,1,12)[1:-1]
torch.linspace(0,1,12)[1:-1]
a = torch.rand(10)
print(a)
print(a.sort())
a.sort()
print(a)
print(sorted(a))
torch.sort(a)


tensor([0.8378, 0.2649, 0.2112, 0.3573, 0.2090, 0.0693, 0.8677, 0.6200, 0.1590,
        0.0067])
torch.return_types.sort(
values=tensor([0.0067, 0.0693, 0.1590, 0.2090, 0.2112, 0.2649, 0.3573, 0.6200, 0.8378,
        0.8677]),
indices=tensor([9, 5, 8, 4, 2, 1, 3, 7, 0, 6]))
tensor([0.8378, 0.2649, 0.2112, 0.3573, 0.2090, 0.0693, 0.8677, 0.6200, 0.1590,
        0.0067])
[tensor(0.0067), tensor(0.0693), tensor(0.1590), tensor(0.2090), tensor(0.2112), tensor(0.2649), tensor(0.3573), tensor(0.6200), tensor(0.8378), tensor(0.8677)]


torch.return_types.sort(
values=tensor([0.0067, 0.0693, 0.1590, 0.2090, 0.2112, 0.2649, 0.3573, 0.6200, 0.8378,
        0.8677]),
indices=tensor([9, 5, 8, 4, 2, 1, 3, 7, 0, 6]))

41. 对于小向量求和时，如何计算才能比使用np.sum更快？
注：在numpy中，可以使用np.add.reduce, 在小向量计算速度上快于np.sum。但pyTorch似乎没有对应的方法，经测试，对torch.arange(10)进行求和时，torch.sum仍然快于np.add.reduce

In [45]:
import time
start_time = time.time()
Z = np.arange(10)
np.add.reduce(Z)
end_time = time.time()
print(end_time-start_time)
start_time = time.time()
Z = torch.arange(10)
torch.sum(Z)
end_time = time.time()
print(end_time-start_time)


0.00019669532775878906
0.0012729167938232422


41.给定两个随机TensorA和B，判断是否相等

In [46]:
A = torch.rand([3,4])
B = torch.rand([3,4])
C = A
print((A == B).sum() == A.numel())
print((A == C).sum() == A.numel())
# 检查值是否精确相等
print(torch.equal(torch.Tensor([1.1, 2.1]), torch.Tensor([1,2])))
# torch.Tensor是一个类，而torch.tensor是一个函数
# 更经常使用torch.tensor，因为它更方便，有自动的类型转换
# 而torch.Tensor确定为torch.float类型
print(torch.equal(torch.tensor([1.1, 2.1]), torch.tensor([1, 2], dtype=torch.float)))
print(torch.allclose(torch.tensor([1.1,2.1]), torch.tensor([1,2], dtype=torch.float), atol=0.1))


tensor(False)
tensor(True)
False
False
True


43. 将Tensor转变为只读

In [47]:
Z = np.zeros(10)
Z.flags.writeable = False
# Z[0] = 2 # read only -> ValueError
A = torch.rand([10,2])*5
# print(A)
B = torch.zeros([10,2])
print(A.square().sum(dim=1))
B[:,0] = torch.sqrt(A.square().sum(dim=1))
B[:,1] = torch.arccos(A[:,0]/ B[:,0])
print(B)
X = A[:,0]
Y = A[:,1]
R = torch.sqrt(X**2 + Y**2)
T = torch.atan(Y/X)
torch.stack([R,T],dim=1)

tensor([ 9.2158,  9.1773, 20.4982, 17.9178,  5.7871, 12.6672,  1.7377,  7.6244,
         3.2433, 15.3436])
tensor([[3.0358e+00, 9.5385e-01],
        [3.0294e+00, 8.5647e-01],
        [4.5275e+00, 1.0795e+00],
        [4.2329e+00, 5.8689e-01],
        [2.4056e+00, 3.9518e-03],
        [3.5591e+00, 1.1017e+00],
        [1.3182e+00, 6.9187e-01],
        [2.7612e+00, 1.0164e-01],
        [1.8009e+00, 4.7685e-02],
        [3.9171e+00, 1.1480e+00]])


tensor([[3.0358e+00, 9.5385e-01],
        [3.0294e+00, 8.5647e-01],
        [4.5275e+00, 1.0795e+00],
        [4.2329e+00, 5.8689e-01],
        [2.4056e+00, 3.9514e-03],
        [3.5591e+00, 1.1017e+00],
        [1.3182e+00, 6.9187e-01],
        [2.7612e+00, 1.0164e-01],
        [1.8009e+00, 4.7685e-02],
        [3.9171e+00, 1.1480e+00]])

In [48]:
t = torch.rand(10)
print(t)
t[torch.argmax(t)] = 0
print(t)
X = torch.linspace(0,1,5)
Z = torch.ones(len(X))
coord = torch.stack([X,X,Z],dim=1)
coord

tensor([0.4620, 0.5805, 0.1659, 0.2199, 0.0962, 0.3451, 0.5704, 0.6778, 0.5864,
        0.6311])
tensor([0.4620, 0.5805, 0.1659, 0.2199, 0.0962, 0.3451, 0.5704, 0.0000, 0.5864,
        0.6311])


tensor([[0.0000, 0.0000, 1.0000],
        [0.2500, 0.2500, 1.0000],
        [0.5000, 0.5000, 1.0000],
        [0.7500, 0.7500, 1.0000],
        [1.0000, 1.0000, 1.0000]])

46. 在直角坐标轴上 (0,0) 到 (1,1) 区域内放一个 5x5 的网格，创建一个5x5x2 的 Tensor，其值对应网格中每个点的坐标

In [49]:
X,Y = torch.meshgrid(torch.linspace(0,1,5),
                     torch.linspace(0,1,5))
torch.stack([X,Y],dim=2)


tensor([[[0.0000, 0.0000],
         [0.0000, 0.2500],
         [0.0000, 0.5000],
         [0.0000, 0.7500],
         [0.0000, 1.0000]],

        [[0.2500, 0.0000],
         [0.2500, 0.2500],
         [0.2500, 0.5000],
         [0.2500, 0.7500],
         [0.2500, 1.0000]],

        [[0.5000, 0.0000],
         [0.5000, 0.2500],
         [0.5000, 0.5000],
         [0.5000, 0.7500],
         [0.5000, 1.0000]],

        [[0.7500, 0.0000],
         [0.7500, 0.2500],
         [0.7500, 0.5000],
         [0.7500, 0.7500],
         [0.7500, 1.0000]],

        [[1.0000, 0.0000],
         [1.0000, 0.2500],
         [1.0000, 0.5000],
         [1.0000, 0.7500],
         [1.0000, 1.0000]]])

47. 给定两个向量X,Y, 创建一个柯西矩阵C(Cij=1/(xi-yj))

In [50]:
X = torch.arange(5)
Y = torch.ones(5)*3
C = torch.ones([5,5])
X.view([-1,1])
print(X.view([-1,1]).shape)
print(X.view([-1,1]) - Y)
torch.div(1, X.view([-1,1]) - Y)


torch.Size([5, 1])
tensor([[-3., -3., -3., -3., -3.],
        [-2., -2., -2., -2., -2.],
        [-1., -1., -1., -1., -1.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 1.,  1.,  1.,  1.,  1.]])


tensor([[-0.3333, -0.3333, -0.3333, -0.3333, -0.3333],
        [-0.5000, -0.5000, -0.5000, -0.5000, -0.5000],
        [-1.0000, -1.0000, -1.0000, -1.0000, -1.0000],
        [    inf,     inf,     inf,     inf,     inf],
        [ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000]])

48. 打印PyTorch Tensor每一种标量数据结构的最大和最小可表示数(representable value)

In [51]:
for dtype in [torch.int8, torch.int32, torch.int64]:
    print(torch.iinfo(dtype).min)
    print(torch.iinfo(dtype).max)

print("=="*8)
for dtype in [torch.float32, torch.float64]:
    print(torch.finfo(dtype).min)
    print(torch.finfo(dtype).max)
    print(torch.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028234663852886e+38
3.4028234663852886e+38
1.1920928955078125e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


49. 如何完整显示 Tensor 的所有值? 

In [52]:
# torch.set_printoptions(threshold=float('NaN'))
Z = torch.zeros([16,16])
print(Z)
torch.set_printoptions(threshold=1000)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0

50. 给定一个标量和一个向量，找出向量中与给定标量值最接近的元素

In [53]:
t = torch.rand(5)
print(t)
scalar = 0.08
b = torch.square(t-scalar)
print(t[torch.argmin(b)])
i = torch.abs(t-scalar).argmin()
print(t[i])

tensor([0.5690, 0.2068, 0.6635, 0.9942, 0.8943])
tensor(0.2068)
tensor(0.2068)


52. 给定一个(100,2)的矩阵，每行表示一个点的坐标。计算所有点两两之间的距离。

In [54]:
A = torch.rand(100,2)*100
def dist_2points(point1, point2):
    vec = point2 - point1
    return torch.sqrt(torch.square(vec).sum())
def dist_2rows(matrix, i, j):
    vec1 = matrix[i,:]
    vec2 = matrix[j,:]
    return dist_2points(vec1, vec2)
print(f"pointA:{A[0,:]}, pointB:{A[5,:]}的距离")
dist_2rows(A, 0, 5)
t = torch.rand([5,2])
X = t[:,0].view([1,-1])
Y = t[:,1].view([1,-1])
print(X.shape)
print((X-X.T).shape)
print(torch.sqrt((X-X.T)**2 + (Y-Y.T)**2))

# 第二种，使用scipy
import scipy
import scipy.spatial
D = scipy.spatial.distance.cdist(t,t)
D


pointA:tensor([98.4723, 42.2691]), pointB:tensor([34.9820, 93.2735])的距离
torch.Size([1, 5])
torch.Size([5, 5])
tensor([[0.0000, 0.0131, 0.4974, 0.3261, 0.6493],
        [0.0131, 0.0000, 0.5000, 0.3285, 0.6503],
        [0.4974, 0.5000, 0.0000, 0.1715, 0.1661],
        [0.3261, 0.3285, 0.1715, 0.0000, 0.3265],
        [0.6493, 0.6503, 0.1661, 0.3265, 0.0000]])


array([[0.        , 0.01310947, 0.49737071, 0.32607643, 0.64927238],
       [0.01310947, 0.        , 0.49998494, 0.3285432 , 0.65031431],
       [0.49737071, 0.49998494, 0.        , 0.17145231, 0.16611076],
       [0.32607643, 0.3285432 , 0.17145231, 0.        , 0.32645763],
       [0.64927238, 0.65031431, 0.16611076, 0.32645763, 0.        ]])

53. 原地将一个浮点型(32 bits) Tensor 转换为整型(32 bits)

In [55]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:]=Z
print(Y)
A = torch.tensor([0.0, 1.2, 3.6], dtype=torch.float32)
print(A.type())
B = A.type(torch.int16)
print(B)

[15 53 33 20 75 36 22 58 84 24]
torch.FloatTensor
tensor([0, 1, 3], dtype=torch.int16)


54. 将一下内容的Tensor保存至硬盘，并再次读取


In [56]:
T = torch.tensor([[1,2,3],
                  [8,9,7],
                  [10, 11, 12]])
torch.save(T,'tensor.pt')
load_tensor = torch.load('tensor.pt')
print(load_tensor)


tensor([[ 1,  2,  3],
        [ 8,  9,  7],
        [10, 11, 12]])


55. enumerate 函数在PyTorch中对应的函数是什么

In [57]:
Z = np.arange(9).reshape(3,3,1)
# ndenumerate 是每一个元素
for index, value in np.ndenumerate(Z):
    print(index, value)

# enumerate 是每一行
for index,value in enumerate(Z):
    print(value, index)


(0, 0, 0) 0
(0, 1, 0) 1
(0, 2, 0) 2
(1, 0, 0) 3
(1, 1, 0) 4
(1, 2, 0) 5
(2, 0, 0) 6
(2, 1, 0) 7
(2, 2, 0) 8
[[0]
 [1]
 [2]] 0
[[3]
 [4]
 [5]] 1
[[6]
 [7]
 [8]] 2


In [58]:
np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))

[array([[-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ],
        [-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
          0.11111111,  0.3333333

57.一个矩阵中随机选p个元素，并替换成其他值

In [59]:
A = torch.ones([5,5])
a = torch.randint(0,5,[3])
b = torch.randint(0,5,[3])
print(A)
A[a,b] = 10
print(A)
p = 3
t = torch.zeros([3,3])
indices = torch.from_numpy(np.random.choice(range(9),p))
# accumulate在重复索引时，可以累加， 正常就是替换值
t.put_(indices, torch.rand(p), accumulate=True)



tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[ 1.,  1.,  1.,  1., 10.],
        [ 1.,  1.,  1.,  1.,  1.],
        [10.,  1., 10.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]])


tensor([[0.0000, 0.0000, 0.0000],
        [0.3268, 0.8912, 0.0000],
        [0.0000, 0.0000, 0.0700]])

58. 给定一个矩阵，计算每个元素减去所在行的平均数


In [60]:
A = torch.rand([5,5])
A_np = A.numpy()
### 注意keepdim=True
# 计算列均值
col_means = np.mean(A_np, axis=1, keepdims=True)  # 形状 (5,)

# 每个元素减去对应行的均值
B = A_np - col_means 
print(B)
print(A - torch.mean(A,dim=1, keepdim=True))
Y = A - A.mean(axis=1,keepdim=True)
Y
X = torch.arange(10).view([2,5]).type(torch.float32)
print("nokeepdim," ,torch.mean(X,dim=1))
print("withkeepdim,", torch.mean(X,dim=1, keepdim=True))




[[ 0.26624596  0.31192893 -0.02594173 -0.11735249 -0.43488085]
 [-0.070508   -0.25434566  0.37285507  0.26254374 -0.31054515]
 [ 0.06071758 -0.52152383  0.2887388  -0.16201949  0.334087  ]
 [-0.39359826 -0.31351632  0.43084347  0.33103502 -0.05476415]
 [-0.097036   -0.27569538  0.3792827   0.17863762 -0.18518907]]
tensor([[ 0.2662,  0.3119, -0.0259, -0.1174, -0.4349],
        [-0.0705, -0.2543,  0.3729,  0.2625, -0.3105],
        [ 0.0607, -0.5215,  0.2887, -0.1620,  0.3341],
        [-0.3936, -0.3135,  0.4308,  0.3310, -0.0548],
        [-0.0970, -0.2757,  0.3793,  0.1786, -0.1852]])
nokeepdim, tensor([2., 7.])
withkeepdim, tensor([[2.],
        [7.]])


59. 给定一个矩阵，根据第n列的值对行进行排序

In [61]:
M = torch.randint(0, 10, [5,2])
n = 1
_, indices = M[:,n].sort()
M = M[indices]

In [86]:
t = torch.randint(0,3,[3,4])
t[:,-1]=0
print(t)
print((t==0).all(dim=0).any().item())

tensor([[1, 2, 0, 0],
        [0, 2, 1, 0],
        [0, 0, 2, 0]])
True


62. 给一个3维数组，计算数组中元素两两之和，得到一个(3,3)的矩阵

In [63]:
a = torch.randint(0,10,(1,3))
b = torch.randint(0,10, (3,1))
print(a)
print(b)
c = a + b
print(c)
A = torch.arange(3).view((1,3))
B = torch.arange(3).view((3,1))
print(A+B)

tensor([[9, 8, 3]])
tensor([[6],
        [9],
        [2]])
tensor([[15, 14,  9],
        [18, 17, 12],
        [11, 10,  5]])
tensor([[0, 1, 2],
        [1, 2, 3],
        [2, 3, 4]])


63. 创建一个继承自Pytorch.Tensor的类，并赋予其name_属性

In [64]:
# class Test(torch.Tensor):
#     def __init__(self, *args, **kwargs):
#         super().__init__(*args, **kwargs)
#         self.name_ = "shui"

# test = Test([1, 2, 3])  # Create a tensor with some data
# print(test.name_)

class NamedTensor(torch.Tensor):
    @staticmethod
    def __new__(cls, x, name, *args, **kwargs):
        obj = super().__new__(cls, x, *args, **kwargs)
        obj.name_ = name
        return obj

Z = NamedTensor(torch.rand([3,3]), "some_name")
Z.name_

'some_name'

In [65]:
# A = torch.tensor([1,1,1])
# B = torch.tensor([1,2,2,2])
# for i in B:
#     A[i] += 1 # source
# print(A)
A = torch.tensor([1, 1, 1], dtype=torch.float32)  # 需要是浮点数
B = torch.tensor([1, 2, 2, 2])                     # 索引
source = torch.ones(B.shape[0])  # 
A.index_add_(0, B, source) # A[index[j]] += source[j] * alpha
print(A)

x = torch.tensor([1, 2, 1, 5, 3, 2, 1])
x = torch.randint(4,9,[10])
print(x)
result = torch.bincount(x)
print(result)  # tensor([1, 3, 2, 1])
result[3]

X = torch.Tensor([1,2,3,4,5,6]).type(torch.int64)
I = torch.Tensor([1,3,9,3,4,1]).type(torch.int64)
F = torch.bincount(I,X)
print(F)


tensor([1., 2., 4.])
tensor([6, 6, 4, 7, 8, 4, 7, 8, 7, 4])
tensor([0, 0, 0, 0, 3, 0, 2, 3, 2])
tensor([0., 7., 0., 6., 5., 0., 0., 0., 0., 3.], dtype=torch.float64)


66. 给定一个(w,h,3)的图像，判断像素中有多少个不重复的点。 

In [66]:
I = torch.randint(0,255,[10,10,3]).type(torch.int8)
F = I[...,0]*256*256 + I[...,1]*256 + I[...,2]
n = len(torch.unique(F))
print(n)

R = 100  # 二进制: 01100100
G = 150  # 二进制: 10010110  
B = 200  # 二进制: 11001000

# 手动计算
F_manual = 100 * 65536 + 150 * 256 + 200
print(f"手动计算: {F_manual}")
print(f"二进制: {bin(F_manual)}")

# 验证
F_calc = (100 << 16) | (150 << 8) | 200
print(f"位运算: {F_calc}")
print(f"是否相等: {F_manual == F_calc}")
print(len(bin(255)))
print(len(bin(256)))


85
手动计算: 6592200
二进制: 0b11001001001011011001000
位运算: 6592200
是否相等: True
10
11


In [67]:
A = torch.randint(0,10,[4,4,3,3])
A.sum(axis=(-1,-2))


tensor([[25, 38, 49, 33],
        [43, 41, 50, 27],
        [24, 41, 30, 45],
        [51, 41, 33, 45]])

68. 给定变量D以及另一个同长度向量S。计算S中所有值相同元素对应的同位置D中的元素的平均数。

In [68]:
D = torch.tensor([1,1,0,1,0])
S = torch.tensor([2,0,3,2,2])
a_sum = torch.bincount(S, weights=D)
D_counts = torch.bincount(S)
D_means = a_sum/D_counts
print(D_means)
import pandas as pd

data = {
    'S': S.numpy(),  # 分组标签
    'D': D.numpy()  # 数据
}
df = pd.DataFrame(data)
result = df.groupby('S')['D'].mean()
print("分组平均值:")
print(result)



tensor([1.0000,    nan, 0.6667, 0.0000], dtype=torch.float64)


分组平均值:
S
0    1.000000
2    0.666667
3    0.000000
Name: D, dtype: float64


In [ ]:
A = torch.randint(0,10,[2,3])
B = torch.randint(0,10,[3,2])
C = A@B
print(C.diag())
print(torch.sum(C.diag()))
print(torch.diagonal(torch.mm(A,B)))
print(A*B.T)
print(torch.sum(A*B.T, axis=1))
print(torch.einsum("ij,ji->i", A, B))  #结果[i] = Σ_j A[i,j] × B[j,i]

tensor([76, 34])
tensor(110)
tensor([76, 34])
tensor([[ 4, 72,  0],
        [ 0, 32,  2]])
tensor([76, 34])
tensor([76, 34])


70. 给定向量 [1, 2, 3, 4, 5]，所有元素之间插入 3 个 0，得到新向量 [1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]

In [70]:
t = torch.Tensor([1,2,3,4,5])
t0 = torch.zeros([len(t) + (len(t)-1)*3])
t0[::4] = t
print(t0)
print(t0[::2])

tensor([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])
tensor([1., 0., 2., 0., 3., 0., 4., 0., 5.])


In [71]:
A = torch.ones((5,5,3))
B = torch.ones((5,5))*2
A * B[:,:,None]
B_expanded = B.unsqueeze(-1)
result1 = A * B_expanded
print(result1)
A * B.view(5,5,1)  # 一定要升维，而不是降维处理
# A_sum = A.sum(dim=-1)
# result = A_sum * B
# print(result)




# D = C@B
# D
# C = A[:,:,0]@B
# C
               

tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])


tensor([[[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]],

        [[2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.],
         [2., 2., 2.]]])

In [72]:
A = torch.arange(25).view(5,5)
A[[0,2]] = A[[2,0]]
print(A)

tensor([[10, 11, 12, 13, 14],
        [ 5,  6,  7,  8,  9],
        [ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])


74. 给定向量C是bincount函数的运行结果，如何计算出向量A，使得torch.bincount(A)==C?

In [73]:
C = torch.tensor([0,2,4,5])
A = torch.tensor([], dtype=torch.long)
for index,i in enumerate(C):
    if i!=0:
        ones = torch.ones(int(i), dtype=torch.long) * index
        A = torch.cat([A, ones])
print(torch.bincount(A))

t = torch.Tensor([1,1,2,3,4,4,6]).type(torch.int64)
C = torch.bincount(t)
T = torch.repeat_interleave(torch.arange(len(C)),C)
b = torch.repeat_interleave(torch.tensor([1,2,4,5]), torch.tensor([2,3,0,1]))
print(T)
print(b)



tensor([0, 2, 4, 5])
tensor([1, 1, 2, 3, 4, 4, 6])
tensor([1, 1, 2, 2, 2, 5])


75. 计算一个一维Tensor每个滑动窗口(sliding window)的平均数

In [74]:
A = torch.arange(25).type(torch.int16)
def moving_average(A, window):
    n = len(A)
    result = []
    for i in range(n-window+1):
        window_sum = A[i:i+window].sum()
        # print(A[i:i+window])
        # print(window_sum/window)
        result.append(window_sum/window)
    return torch.tensor(result, dtype=torch.float32)
print(moving_average(A,3))

def moving_average(a, n=3):
    ret = torch.cumsum(a, dim=0)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n-1:] /n
Z = torch.arange(20)
print(moving_average(Z, 3))



tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18., 19., 20., 21., 22., 23.])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.,
        15., 16., 17., 18.])


76. 给定一个一维 Tensor Z，创建一个二维 Tensor，其第一行是 (Z[0],Z[1],Z[2])，其后的每一行是上一行再后延 1 位（第二行就是 (Z[1],Z[2],Z[3])，最后一行就是 (Z[-3],Z[-2],Z[-1])）(★★★)

In [75]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window +1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape,strides=strides)
# as_strided创建了一个视图（不是副本）：
a = np.arange(10)
Z = rolling(a, 3)
print(Z)
a[5] = 100
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[  0   1   2]
 [  1   2   3]
 [  2   3   4]
 [  3   4 100]
 [  4 100   6]
 [100   6   7]
 [  6   7   8]
 [  7   8   9]]


In [76]:
A = torch.randint(0,10, [5])
B = A>5
print(B)
B[:] = ~B[:]
print(B)
torch.logical_not(B,out=B)
print(B)
D = torch.randn([5])
print(D)
D = D*-1
print(D)
torch.neg(D, out=D)
print(D)

tensor([False,  True,  True,  True, False])
tensor([ True, False, False, False,  True])
tensor([False,  True,  True,  True, False])
tensor([ 0.0090,  0.8050, -1.2733, -1.4510,  1.0682])
tensor([-0.0090, -0.8050,  1.2733,  1.4510, -1.0682])
tensor([ 0.0090,  0.8050, -1.2733, -1.4510,  1.0682])


78. P0 和 P1 是两个矩阵，每个矩阵每一行对应一个点的坐标。给定点 p，计算 p 到每一条 (P0[i],P1[i]) 组成的线的距离(★★★)

In [77]:
P0 = torch.arange(10).view([5,2])
P1 = torch.randint(10,[5,2])
def compute_dist(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/ L
    U = U.reshape([len(U),1])
    D = P0 +U*T -p
    return torch.sqrt((D**2).sum(axis=1))

P0 = (torch.rand([10,2]) - 0.5)*20
P1 = (torch.rand([10,2]) - 0.5)*20
p = (torch.rand([1,2]) - 0.5)*20
print(compute_dist(P0, P1, p))

p = (torch.rand([10,2]) - 0.5)*20
print(torch.stack([compute_dist(P0, P1, p_i) for p_i in p]))

def compute_dist_3d(P0, P1, p):
    T = P1 - P0
    w = p - P0

    dot_w_T = torch.sum(w*T, dim=1)
    norm_T_sq = torch.sum(T**2, dim=1)
    t = dot_w_T / norm_T_sq

    proj_point = P0 + t.unsqueeze(1) *T

    v = p-proj_point

    distance = torch.sqrt(torch.sum(v**2, dim=1))

    return distance




    


tensor([13.4386, 12.0983, 12.7036,  6.4963,  0.7720,  4.6535,  0.2261, 12.9893,
         1.4731,  0.7220])
tensor([[ 2.1077, 12.6936,  4.4553,  3.1830,  7.7769, 12.2475, 13.0769,  2.4084,
          4.3368, 11.3206],
        [ 5.5393,  0.1240,  1.1825,  8.5156,  4.8425, 12.8867,  2.6813,  5.8668,
          8.4537,  0.4149],
        [ 2.5433,  0.5660,  4.9238,  7.2023,  5.8930,  8.9155,  0.0591,  2.1159,
          8.5305,  2.3444],
        [ 8.0843, 12.0552,  5.0260,  4.6940,  3.6482,  3.0636,  5.5755,  5.8868,
          2.4581,  5.2578],
        [ 6.2406,  4.2844, 12.6775,  1.5845,  5.7335,  0.7170,  4.0108,  7.5866,
          6.0061,  4.4741],
        [ 1.2704,  1.8482, 13.6378,  7.7021, 11.2114,  1.3893,  7.7250,  4.2499,
         12.0072,  9.1355],
        [ 5.3939,  1.9886,  1.0825,  7.1073,  2.4286, 14.2239,  5.3069,  6.6699,
          6.3654,  2.1753],
        [ 2.5993,  5.4407,  5.8822,  1.9453,  2.1919,  5.5154,  1.7057,  2.1225,
          3.9905,  0.3371],
        [ 8.7901,  0.

In [78]:
a = torch.tensor([1,2,3]).view([1,3])
b = torch.tensor([2,3,4]).view([1,3])
dot = torch.sum(a*b,dim=1)
print((a@b.T).squeeze(1))
print(dot)

tensor([20])
tensor([20])


In [79]:
from numpy.lib import stride_tricks
def rolling(a,window):
    shape = (a.size - window +1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(14)+1, 4)
print(Z)

Z = np.arange(1,15, dtype=np.uint32)
print(Z.itemsize)
R = stride_tricks.as_strided(Z, (11,4), (4,4))
print(R)






[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
4
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


82. 计算一个矩阵的秩

In [80]:
A = torch.tensor([[1,1,1],[0,1,0],[1,1,1]],dtype=torch.float)
A = torch.rand((10,10))
print(torch.matrix_rank(A))
S = torch.linalg.svdvals(A)
tol = 1e-22
if tol is None:
    eps = torch.finfo(S.dtype).eps
    tol = S.max()*max(A.shape)*eps
rank = torch.sum(S>tol).item()
print(rank)

U, S, V = torch.svd(A)
rank = torch.sum(S>1e-10)
print(rank)

a = torch.randint(0,2, [10])
print(a)
b = torch.argmax(torch.bincount(a))
print(b)
torch.mode(a)



tensor(10)
10
tensor(10)
tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 1])
tensor(0)


torch.return_types.mode(
values=tensor(0),
indices=tensor(8))

84. 从一个10x10的矩阵中，提取出所有的连续3x3小矩阵

In [81]:
A = torch.rand([4,4])*10
b = torch.stack([A[i:i+3, j:j+3] for i in range(A.shape[0]-2) for j in range(A.shape[1]-2) ])

# print(b)
b.shape

"""更高效"""
# 原始Z: m×n矩阵
# 内存布局: 行主序
# Z.stride(): (n, 1)  # 行跨步=n，列跨步=1
Z = A
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1] -3)
C = torch.as_strided(Z,size=[i,j,3,3], stride=Z.stride() + Z.stride())
# print(C)
A[0,3] = 50
print(b)
print(C)

tensor([[[1.3922, 1.6347, 6.5040],
         [7.5139, 2.6396, 5.6477],
         [3.2308, 5.0328, 9.9290]],

        [[1.6347, 6.5040, 9.2954],
         [2.6396, 5.6477, 0.3469],
         [5.0328, 9.9290, 5.9292]],

        [[7.5139, 2.6396, 5.6477],
         [3.2308, 5.0328, 9.9290],
         [5.2064, 4.1453, 9.2024]],

        [[2.6396, 5.6477, 0.3469],
         [5.0328, 9.9290, 5.9292],
         [4.1453, 9.2024, 1.2758]]])
tensor([[[[ 1.3922,  1.6347,  6.5040],
          [ 7.5139,  2.6396,  5.6477],
          [ 3.2308,  5.0328,  9.9290]],

         [[ 1.6347,  6.5040, 50.0000],
          [ 2.6396,  5.6477,  0.3469],
          [ 5.0328,  9.9290,  5.9292]]],


        [[[ 7.5139,  2.6396,  5.6477],
          [ 3.2308,  5.0328,  9.9290],
          [ 5.2064,  4.1453,  9.2024]],

         [[ 2.6396,  5.6477,  0.3469],
          [ 5.0328,  9.9290,  5.9292],
          [ 4.1453,  9.2024,  1.2758]]]])


85. 创建一个 class，输入一个矩阵，将其转换为对称矩阵，同时要确保转换后的对称矩阵任意一个元素修改值后，对称位置元素也要修改 (★★★)

In [82]:
class Symetric:
    def __init__(self, x:torch.tensor):
        self.tensor = x + x.T
    
    def __setitem__(self, index, value):
        i,j = index
        self.tensor.__setitem__((i,j), value)
        self.tensor.__setitem__((j,i), value)

    def __repr__(self):
        return self.tensor.__repr__()

t = Symetric(torch.arange(16).view(4,4))
print(t)
t[2,3] = 42
print(t)


tensor([[ 0,  5, 10, 15],
        [ 5, 10, 15, 20],
        [10, 15, 20, 25],
        [15, 20, 25, 30]])
tensor([[ 0,  5, 10, 15],
        [ 5, 10, 15, 20],
        [10, 15, 20, 42],
        [15, 20, 42, 30]])


In [83]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                    np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


88.使用Tensor实现生命游戏(Game of Life)(★★★)
译者注：生命游戏见 https://zh.wikipedia.org/wiki/%E5%BA%B7%E5%A8%81%E7%94%9F%E5%91%BD%E6%B8%B8%E6%88%8F

In [84]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2, 0:-2] + Z[0:-2, 1:-1] + Z[0:-2, 2:] +
         Z[1:-1, 0:-2]                 + Z[1:-1, 2:] + 
         Z[2:  , 0:-2] + Z[2:  , 1:-1] + Z[2:  , 2:])
    print(N)
    print(Z[1:-1, 1:-1] )
    # Apply rules
    birth = (N==3) & (Z[1:-1, 1:-1] == 0)
    survive = (N==2) | (N==3) & (Z[1:-1, 1:-1] == 1)
    Z[...] = 0
    Z[1:-1, 1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(5,5))
print(Z)
for i in range(100):
    Z = iterate(Z)
    print(Z)

[[0 1 0 0 0]
 [0 1 1 1 0]
 [0 0 0 0 0]
 [1 0 0 1 1]
 [0 1 1 1 0]]
[[2 3 1]
 [3 4 4]
 [3 4 3]]
[[1 1 1]
 [0 0 0]
 [0 0 1]]
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 1 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]
[[2 2 1]
 [3 5 2]
 [1 3 0]]
[[1 1 0]
 [1 0 0]
 [1 0 1]]
[[0 0 0 0 0]
 [0 1 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[2 3 2]
 [3 5 2]
 [2 2 2]]
[[1 1 0]
 [1 0 1]
 [0 1 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[2 4 2]
 [4 8 4]
 [2 4 2]]
[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]
[[0 2 0]
 [2 4 2]
 [0 2 0]]
[[1 0 1]
 [0 0 0]
 [1 0 1]]
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 0]
 [0 0 0 0 0]]
[[2 2 2]
 [2 4 2]
 [2 2 2]]
[[0 1 0]
 [1 0 1]
 [0 1 0]]
[[0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 1 0]
 [0 1 1 1 0]
 [0 0 0 0 0]]
[[2 4 2]
 [4 8 4]
 [2 4 2]]
[[1 1 1]
 [1 0 1]
 [1 1 1]]
[[0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]
 [0 1 0 1 0]
 [0 0 0 0 0]]
[[0 2 0]
 [2 4 2]
 [0 2 0]]
[[1 0 1]
 [0 0 0]
 [1 0 1]]
[[0 0 0 0 0]
 [0 0 1 0 0